version: '3.8'
services:
  cloud-db:
    container_name: tensile-cloud-db
    image: postgres
    restart: always
    ports:
      - "54301:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: root
      POSTGRES_DB: cloud
  api:
    build:
      context: .
      dockerfile: "./docker/api/Dockerfile"
    container_name: tensile-cloud-api
    volumes:
      - "myapp:/home/app"
    networks:
      - default
    ports:
      - "9090:9090"
volumes:
  myapp:
    external: true